# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [developers/lonycell/master]

jobs:
  stop-servers:
    name: stop-servers
    runs-on: self-hosted
    steps:
      - name: Stop Servers
        run: |
          pm2 stop hubs_server
          pm2 delete hubs_server
          pm2 stop hubs_admin_server
          pm2 delete hubs_admin_server
        continue-on-error: true

  hubs-server:
    name: hubs-server
    needs: stop-servers
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache hubs_server dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: hubs-${{ hashFiles('package-lock.json') }}

      - name: Install dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

  hubs-admin:
    name: hubs-admin
    needs: hubs-server
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Stop Server (hubs_admin_server)
        run: |
          pm2 stop hubs_admin_server
          pm2 delete hubs_admin_server
        continue-on-error: true

      - name: change Working Directory
        run: |
          cd admin/

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache hubs_admin_server dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: admin-${{ hashFiles('package-lock.json') }}

      - name: Install dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  run-servers:
    name: run-servers
    needs: hubs-admin
    runs-on: self-hosted
    steps:
      - name: Run Servers
        run: |
          pm2 start "npm run prod" --name hubs_server
          pm2 start "npm run prod" --name hubs_admin_server