# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [developers/lonycell/master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Stop Server (hubs_server)
        run: |
          pm2 stop hubs_server
          pm2 delete hubs_server
        continue-on-error: true

      - name: Stop Server (hubs_admin_server)
        run: |
          pm2 stop hubs_admin_server
          pm2 delete hubs_admin_server
        continue-on-error: true

      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache hubs_server dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Cache hubs_server dependencies
        uses: actions/cache@v3
        run: |
          cd admin/
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install hubs admin deps
        run: |
          pwd
          npm ci --ignore-scripts
          ls
          cd ..

      - name: Register hubs server to PM2
        run: |
          pm2 start "npm run prod" --name hubs_server

      - name: Register hubs admin server to PM2
        run: |
          cd admin/
          pm2 start "npm run prod" --name hubs_admin_server
